name: ails
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python >= 3.7
  - h5py = 2.10.0
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - tensorboard
  - rdkit
  - lightgbm
  - keras >2.1,<2.3.1
  - tensorflow >1.8,<2.1
  - pillow=6.2.1
  - pip:
    - fcd